
spring:
  application:
    name: cdms
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: CDMS
    password: CDMS
    driver-class-name: oracle.jdbc.OracleDriver
  redis:
    host: localhost
    port: 6379
    database: 2
    # password:  #默认为空
    lettuce:
      pool:
        max-active: 30  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 10     #最大空闲连接，默认8
        min-idle: 3     #最小空闲连接，默认3
#logging:
#  level:
#    org:
#      hibernate:
#        type.descriptor.sql.BasicBinder: trace
#        SQL: DEBUG
#    com:
#      bob:
#        cdms: DEBUG

mpp:
  entityBasePath: com.bob.cdms.entity